# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [18]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset [wind.csv](https://github.com/guipsamora/pandas_exercises/blob/master/Stats/Wind_Stats/wind.data) from the folder

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [62]:
data = pd.read_csv("C:/Users/Latha/Documents/wind.data")

In [63]:
data.tail(5)

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
6569,78,12,27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
6570,78,12,28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
6571,78,12,29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
6572,78,12,30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
6573,78,12,31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

In [21]:
data.dtypes

Yr       int64
Mo       int64
Dy       int64
RPT    float64
VAL    float64
ROS    float64
KIL    float64
SHA    float64
BIR    float64
DUB    float64
CLA    float64
MUL    float64
CLO    float64
BEL    float64
MAL    float64
dtype: object

In [75]:
YMD = pd.to_datetime(+data.Dy,format='%Y/%m/%d')
#print(data['Yr'])
YMD

0      1970-01-01 00:00:00.000000001
1      1970-01-01 00:00:00.000000002
2      1970-01-01 00:00:00.000000003
3      1970-01-01 00:00:00.000000004
4      1970-01-01 00:00:00.000000005
5      1970-01-01 00:00:00.000000006
6      1970-01-01 00:00:00.000000007
7      1970-01-01 00:00:00.000000008
8      1970-01-01 00:00:00.000000009
9      1970-01-01 00:00:00.000000010
10     1970-01-01 00:00:00.000000011
11     1970-01-01 00:00:00.000000012
12     1970-01-01 00:00:00.000000013
13     1970-01-01 00:00:00.000000014
14     1970-01-01 00:00:00.000000015
15     1970-01-01 00:00:00.000000016
16     1970-01-01 00:00:00.000000017
17     1970-01-01 00:00:00.000000018
18     1970-01-01 00:00:00.000000019
19     1970-01-01 00:00:00.000000020
20     1970-01-01 00:00:00.000000021
21     1970-01-01 00:00:00.000000022
22     1970-01-01 00:00:00.000000023
23     1970-01-01 00:00:00.000000024
24     1970-01-01 00:00:00.000000025
25     1970-01-01 00:00:00.000000026
26     1970-01-01 00:00:00.000000027
27     1970-01-01 00:00:00.000000028
28     1970-01-01 00:00:00.000000029
29     1970-01-01 00:00:00.000000030
                    ...
6544   1970-01-01 00:00:00.000000002
6545   1970-01-01 00:00:00.000000003
6546   1970-01-01 00:00:00.000000004
6547   1970-01-01 00:00:00.000000005
6548   1970-01-01 00:00:00.000000006
6549   1970-01-01 00:00:00.000000007
6550   1970-01-01 00:00:00.000000008
6551   1970-01-01 00:00:00.000000009
6552   1970-01-01 00:00:00.000000010
6553   1970-01-01 00:00:00.000000011
6554   1970-01-01 00:00:00.000000012
6555   1970-01-01 00:00:00.000000013
6556   1970-01-01 00:00:00.000000014
6557   1970-01-01 00:00:00.000000015
6558   1970-01-01 00:00:00.000000016
6559   1970-01-01 00:00:00.000000017
6560   1970-01-01 00:00:00.000000018
6561   1970-01-01 00:00:00.000000019
6562   1970-01-01 00:00:00.000000020
6563   1970-01-01 00:00:00.000000021
6564   1970-01-01 00:00:00.000000022
6565   1970-01-01 00:00:00.000000023
6566   1970-01-01 00:00:00.000000024
6567   1970-01-01 00:00:00.000000025
6568   1970-01-01 00:00:00.000000026
6569   1970-01-01 00:00:00.000000027
6570   1970-01-01 00:00:00.000000028
6571   1970-01-01 00:00:00.000000029
6572   1970-01-01 00:00:00.000000030
6573   1970-01-01 00:00:00.000000031
Name: Dy, Length: 6574, dtype: datetime64[ns]

In [78]:
ymd = pd.to_datetime(data.Yr*10000+data.Mo*100+data.Dy,format='%Y-%m-%d')

0      1970-01-01 00:00:00.000610101
1      1970-01-01 00:00:00.000610102
2      1970-01-01 00:00:00.000610103
3      1970-01-01 00:00:00.000610104
4      1970-01-01 00:00:00.000610105
5      1970-01-01 00:00:00.000610106
6      1970-01-01 00:00:00.000610107
7      1970-01-01 00:00:00.000610108
8      1970-01-01 00:00:00.000610109
9      1970-01-01 00:00:00.000610110
10     1970-01-01 00:00:00.000610111
11     1970-01-01 00:00:00.000610112
12     1970-01-01 00:00:00.000610113
13     1970-01-01 00:00:00.000610114
14     1970-01-01 00:00:00.000610115
15     1970-01-01 00:00:00.000610116
16     1970-01-01 00:00:00.000610117
17     1970-01-01 00:00:00.000610118
18     1970-01-01 00:00:00.000610119
19     1970-01-01 00:00:00.000610120
20     1970-01-01 00:00:00.000610121
21     1970-01-01 00:00:00.000610122
22     1970-01-01 00:00:00.000610123
23     1970-01-01 00:00:00.000610124
24     1970-01-01 00:00:00.000610125
25     1970-01-01 00:00:00.000610126
26     1970-01-01 00:00:00.000610127
27     1970-01-01 00:00:00.000610128
28     1970-01-01 00:00:00.000610129
29     1970-01-01 00:00:00.000610130
                    ...
6544   1970-01-01 00:00:00.000781202
6545   1970-01-01 00:00:00.000781203
6546   1970-01-01 00:00:00.000781204
6547   1970-01-01 00:00:00.000781205
6548   1970-01-01 00:00:00.000781206
6549   1970-01-01 00:00:00.000781207
6550   1970-01-01 00:00:00.000781208
6551   1970-01-01 00:00:00.000781209
6552   1970-01-01 00:00:00.000781210
6553   1970-01-01 00:00:00.000781211
6554   1970-01-01 00:00:00.000781212
6555   1970-01-01 00:00:00.000781213
6556   1970-01-01 00:00:00.000781214
6557   1970-01-01 00:00:00.000781215
6558   1970-01-01 00:00:00.000781216
6559   1970-01-01 00:00:00.000781217
6560   1970-01-01 00:00:00.000781218
6561   1970-01-01 00:00:00.000781219
6562   1970-01-01 00:00:00.000781220
6563   1970-01-01 00:00:00.000781221
6564   1970-01-01 00:00:00.000781222
6565   1970-01-01 00:00:00.000781223
6566   1970-01-01 00:00:00.000781224
6567   1970-01-01 00:00:00.000781225
6568   1970-01-01 00:00:00.000781226
6569   1970-01-01 00:00:00.000781227
6570   1970-01-01 00:00:00.000781228
6571   1970-01-01 00:00:00.000781229
6572   1970-01-01 00:00:00.000781230
6573   1970-01-01 00:00:00.000781231
Length: 6574, dtype: datetime64[ns]

In [55]:
data['Corrected_year'] = YMD

In [56]:
data.head(2)

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,Corrected_year
0,4061,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1970-01-01 00:00:00.040610101
1,4061,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,1970-01-01 00:00:00.040610102

In [34]:
data.dtypes

Yr                         int64
Mo                         int64
Dy                         int64
RPT                      float64
VAL                      float64
ROS                      float64
KIL                      float64
SHA                      float64
BIR                      float64
DUB                      float64
CLA                      float64
MUL                      float64
CLO                      float64
BEL                      float64
MAL                      float64
Corrected_year    datetime64[ns]
dtype: object

In [51]:
data.shape

(6574, 13)

In [25]:
data = data.drop(['Yr','Mo','Dy'], axis = 1)

In [26]:
data.dtypes

RPT                      float64
VAL                      float64
ROS                      float64
KIL                      float64
SHA                      float64
BIR                      float64
DUB                      float64
CLA                      float64
MUL                      float64
CLO                      float64
BEL                      float64
MAL                      float64
Corrected_year    datetime64[ns]
dtype: object

In [50]:
data.columns.values

array(['RPT', 'VAL', 'ROS', 'KIL', 'SHA', 'BIR', 'DUB', 'CLA', 'MUL',
       'CLO', 'BEL', 'MAL', 'Corrected_year'], dtype=object)

In [29]:
data = data[['Corrected_year','RPT','VAL','ROS','KIL','SHA','BIR','DUB','CLA','MUL','CLO','BEL','MAL']]

In [30]:
data.dtypes

Corrected_year    datetime64[ns]
RPT                      float64
VAL                      float64
ROS                      float64
KIL                      float64
SHA                      float64
BIR                      float64
DUB                      float64
CLA                      float64
MUL                      float64
CLO                      float64
BEL                      float64
MAL                      float64
dtype: object

### Step 4. Year 2061 is seemingly imporoper. Convert every year which are < 70 to 19XX instead of 20XX.

In [57]:
 nw_yr =data['Yr'] 
data['Yr'] = np.where(nw_yr <= 20, 2000 + nw_yr, 1900 + nw_yr)

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [32]:
data.index=data['Corrected_year']

In [33]:
data

,Corrected_year,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Corrected_year,,,,,,,,,,,,,
1970-01-01 00:00:00.000610101,1970-01-01 00:00:00.000610101,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1970-01-01 00:00:00.000610102,1970-01-01 00:00:00.000610102,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1970-01-01 00:00:00.000610103,1970-01-01 00:00:00.000610103,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1970-01-01 00:00:00.000610104,1970-01-01 00:00:00.000610104,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1970-01-01 00:00:00.000610105,1970-01-01 00:00:00.000610105,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
1970-01-01 00:00:00.000610106,1970-01-01 00:00:00.000610106,13.21,8.12,9.96,6.67,5.37,4.50,10.67,4.42,7.17,7.50,8.12,13.17
1970-01-01 00:00:00.000610107,1970-01-01 00:00:00.000610107,13.50,14.29,9.50,4.96,12.29,8.33,9.17,9.29,7.58,7.96,13.96,13.79
1970-01-01 00:00:00.000610108,1970-01-01 00:00:00.000610108,10.96,9.75,7.62,5.91,9.62,7.29,14.29,7.62,9.25,10.46,16.62,16.46
1970-01-01 00:00:00.000610109,1970-01-01 00:00:00.000610109,12.58,10.83,10.00,4.75,10.37,6.79,8.04,10.13,7.79,9.08,13.04,15.37
1970-01-01 00:00:00.000610110,1970-01-01 00:00:00.000610110,13.37,11.12,19.50,8.33,9.71,6.54,11.42,7.79,8.54,9.00,8.58,11.83
1970-01-01 00:00:00.000610111,1970-01-01 00:00:00.000610111,10.58,9.87,8.42,2.79,8.71,7.25,7.54,8.33,5.71,8.67,20.71,16.92
1970-01-01 00:00:00.000610112,1970-01-01 00:00:00.000610112,19.75,12.08,18.50,10.54,10.29,9.46,15.54,11.50,10.37,14.58,15.59,14.09
1970-01-01 00:00:00.000610113,1970-01-01 00:00:00.000610113,9.92,3.54,8.46,2.96,2.29,0.96,4.63,0.58,2.33,3.37,5.25,7.04
1970-01-01 00:00:00.000610114,1970-01-01 00:00:00.000610114,9.04,5.66,7.08,0.67,2.71,1.38,3.08,2.58,0.50,2.67,7.17,5.17
1970-01-01 00:00:00.000610115,1970-01-01 00:00:00.000610115,12.04,9.67,11.75,2.37,7.38,3.13,2.50,6.83,4.75,5.63,7.54,6.75
1970-01-01 00:00:00.000610116,1970-01-01 00:00:00.000610116,16.42,11.25,15.67,4.71,11.34,6.92,9.25,8.79,8.21,7.33,13.04,9.04
1970-01-01 00:00:00.000610117,1970-01-01 00:00:00.000610117,17.75,14.37,17.33,10.13,13.96,13.37,13.42,11.04,8.71,11.38,15.92,16.08
1970-01-01 00:00:00.000610118,1970-01-01 00:00:00.000610118,19.83,12.04,20.79,18.54,NaN,10.29,17.83,11.38,14.67,16.71,8.79,17.96
1970-01-01 00:00:00.000610119,1970-01-01 00:00:00.000610119,4.92,3.42,7.29,1.04,3.67,3.17,3.71,2.79,1.92,2.71,6.87,7.83
1970-01-01 00:00:00.000610120,1970-01-01 00:00:00.000610120,9.59,11.83,7.96,1.58,7.92,5.00,3.17,4.92,3.13,3.37,6.50,6.79
1970-01-01 00:00:00.000610121,1970-01-01 00:00:00.000610121,14.33,10.25,11.92,6.13,10.04,7.67,8.04,9.17,7.04,7.87,6.75,12.42
1970-01-01 00:00:00.000610122,1970-01-01 00:00:00.000610122,9.59,5.88,9.92,2.17,6.87,5.50,9.38,7.04,6.34,7.50,10.88,9.92
1970-01-01 00:00:00.000610123,1970-01-01 00:00:00.000610123,16.54,9.96,18.54,10.46,13.50,12.67,13.70,13.75,10.75,13.17,14.79,20.58
1970-01-01 00:00:00.000610124,1970-01-01 00:00:00.000610124,25.04,14.83,25.84,15.67,21.46,18.58,20.38,19.38,15.37,15.12,23.09,25.25
1970-01-01 00:00:00.000610125,1970-01-01 00:00:00.000610125,13.62,11.17,12.67,6.04,10.00,9.42,9.25,8.71,7.12,12.04,14.04,17.50
1970-01-01 00:00:00.000610126,1970-01-01 00:00:00.000610126,24.37,18.79,17.50,14.25,18.91,15.67,14.33,15.16,16.08,19.08,20.50,25.25
1970-01-01 00:00:00.000610127,1970-01-01 00:00:00.000610127,22.04,20.79,17.41,16.21,19.04,16.13,16.79,18.29,18.66,19.08,26.08,27.63
1970-01-01 00:00:00.000610128,1970-01-01 00:00:00.000610128,17.67,13.54,13.33,8.87,15.04,11.63,12.25,10.58,11.92,11.04,20.30,18.12
1970-01-01 00:00:00.000610129,1970-01-01 00:00:00.000610129,NaN,23.91,22.29,17.54,24.08,19.70,22.00,20.25,21.46,19.95,27.71,23.38
1970-01-01 00:00:00.000610130,1970-01-01 00:00:00.000610130,12.21,11.42,10.92,7.92,13.08,9.62,14.50,10.21,9.92,11.96,18.88,19.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970-01-01 00:00:00.000781202,1970-01-01 00:00:00.000781202,13.70,12.71,14.29,5.13,9.21,8.04,12.33,6.34,9.21,11.21,9.59,19.95
1970-01-01 00:00:00.000781203,1970-01-01 00:00:00.000781203,21.21,21.34,17.75,11.58,16.75,14.46,17.46,15.29,15.79,17.50,21.42,25.75
1970-01-01 00:00:00.000781204,1970-01-01 00:00:00.000781204,9.92,13.50,7.21,1.71,11.00,7.50,8.38,7.46,10.79,10.21,17.88,17.96
1970-01-01 00:00:00.000781205,1970-01-01 00:00:00.000781205,22.75,20.17,18.58,8.50,15.96,14.29,13.92,12.92,12.96,12.29,17.08,19.83
1970-01-01 00:00:00.000781206,1970-01-01 00:00:00.000781206,29.33,23.87,25.37,16.04,24.46,19.50,24.54,18.58,21.00,20.58,21.67,34.46
1970-01-01 00:00:00.000781207,1970-01-01 00:00:00.000781207,26.63,24.79,24.79,18.16,23.13,19.58,19.92,19.04,19.75,21.50,23.04,34.59
1970-01-01 00:00:00.000781208,1970-01-01 00:00:00.000781208,12.92,12.54,11.25,3.37,6.50,5.96,10.34,6.17,6.63,6.75,9.54,17.33
1970-01-01 00:00:00.000781209,1970-01-01 00:00:00.000781209,18.71,16.92,15.50,6.04,10.37,9.59,10.75,9.13,9.75,11.08,14.33,15.34
1970-01-01 00:00:00.000781210,1970-01-01 00:00:00.000781210,24.92,22.54,16.54,14.62,15.59,13.00,13.21,14.12,16.21,16.17,26.08,21.92
1970-01-01 00:00:00.000781211,1970-01-01 00:00:00.000781211,20.25,19.17,17.83,11.63,17.79,13.37,14.83,13.88,15.54,16.29,18.34,22.83
1970-01-01 00:00:00.000781212,1970-01-01 00:00:00.000781212,23.13,18.63,18.05,8.29,14.33,11.04,10.54,10.13,11.42,10.50,11.25,13.50
1970-01-01 00:00:00.000781213,1970-01-01 00:00:00.000781213,18.84,24.04,14.37,8.33,18.12,12.17,13.00,13.75,14.17,15.09,21.50,21.37
1970-01-01 00:00:00.000781214,1970-01-01 00:00:00.000781214,17.21,19.75,12.71,5.83,13.79,7.33,8.83,5.71,7.96,3.37,5.21,6.92
1970-01-01 00:00:00.000781215,1970-01-01 00:00:00.000781215,13.13,8.92,16.54,6.92,6.00,4.00,12.67,5.88,7.67,6.08,5.50,17.16
1970-01-01 00:00:00.000781216,1970-01-01 00:00:00.000781216,14.88,9.13,17.37,5.21,6.71,2.46,9.13,4.96,6.13,5.96,10.92,18.08
1970-01-01 00:00:00.000781217,1970-01-01 00:00:00.000781217,9.87,3.21,8.04,2.21,3.04,0.54,2.46,1.46,1.29,2.67,5.00,9.08
1970-01-01 00:00:00.000781218,1970-01-01 00:00:00.000781218,9.83,10.88,8.50,1.00,9.08,6.00,2.42,8.25,4.42,5.88,19.79,19.79
1970-01-01 00:00:00.000781219,1970-01-01 00:00:00.000781219,13.88,11.42,10.13,2.33,8.12,6.75,4.75,5.88,6.21,8.17,8.33,18.25
1970-01-01 00:00:00.000781220,1970-01-01 00:00:00.000781220,9.92,3.63,12.38,3.08,3.50,0.42,4.54,2.50,2.13,4.71,3.21,10.29
1970-01-01 00:00:00.000781221,1970-01-01 00:00:00.000781221,12.96,3.83,13.79,4.79,7.12,6.54,11.67,9.25,8.67,9.00,11.25,20.30
1970-01-01 00:00:00.000781222,1970-01-01 00:00:00.000781222,6.21,7.38,13.08,2.54,7.58,5.33,2.46,8.38,5.09,5.04,9.92,11.00
1970-01-01 00:00:00.000781223,1970-01-01 00:00:00.000781223,16.62,13.29,22.21,9.50,14.29,13.08,16.50,17.16,12.71,12.00,18.50,21.50
1970-01-01 00:00:00.000781224,1970-01-01 00:00:00.000781224,8.67,5.63,12.12,4.79,5.09,5.91,12.25,9.25,10.83,11.71,11.92,31.71
1970-01-01 00:00:00.000781225,1970-01-01 00:00:00.000781225,7.21,6.58,7.83,2.67,4.79,4.58,8.71,0.75,5.21,5.25,1.21,13.96
1970-01-01 00:00:00.000781226,1970-01-01 00:00:00.000781226,13.83,11.87,10.34,2.37,6.96,4.29,1.96,3.79,3.04,3.08,4.79,11.96
1970-01-01 00:00:00.000781227,1970-01-01 00:00:00.000781227,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
1970-01-01 00:00:00.000781228,1970-01-01 00:00:00.000781228,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
1970-01-01 00:00:00.000781229,1970-01-01 00:00:00.000781229,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
1970-01-01 00:00:00.000781230,1970-01-01 00:00:00.000781230,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
1970-01-01 00:00:00.000781231,1970-01-01 00:00:00.000781231,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

In [91]:
data.tail(4)

,Corrected_year,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Corrected_year,,,,,,,,,,,,,
1978-12-28,1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
1978-12-29,1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
1978-12-30,1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
1978-12-31,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

In [39]:
data.tail(4)

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
6570,78,12,28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
6571,78,12,29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
6572,78,12,30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
6573,78,12,31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [64]:
data.isnull().sum()

Corrected_year    0
RPT               6
VAL               3
ROS               2
KIL               5
SHA               2
BIR               0
DUB               3
CLA               2
MUL               3
CLO               1
BEL               0
MAL               4
dtype: int64

In [76]:
data.fillna('NaN')

,Corrected_year,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Corrected_year,,,,,,,,,,,,,
1961-01-01,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,1961-01-02,14.71,NaN,10.83,6.5,12.62,7.67,11.5,10.04,9.79,9.67,17.54,13.83
1961-01-03,1961-01-03,18.5,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.5,7.67,12.75,12.71
1961-01-04,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
1961-01-06,1961-01-06,13.21,8.12,9.96,6.67,5.37,4.50,10.67,4.42,7.17,7.5,8.12,13.17
1961-01-07,1961-01-07,13.5,14.29,9.5,4.96,12.29,8.33,9.17,9.29,7.58,7.96,13.96,13.79
1961-01-08,1961-01-08,10.96,9.75,7.62,5.91,9.62,7.29,14.29,7.62,9.25,10.46,16.62,16.46
1961-01-09,1961-01-09,12.58,10.83,10,4.75,10.37,6.79,8.04,10.13,7.79,9.08,13.04,15.37
1961-01-10,1961-01-10,13.37,11.12,19.5,8.33,9.71,6.54,11.42,7.79,8.54,9,8.58,11.83
1961-01-11,1961-01-11,10.58,9.87,8.42,2.79,8.71,7.25,7.54,8.33,5.71,8.67,20.71,16.92
1961-01-12,1961-01-12,19.75,12.08,18.5,10.54,10.29,9.46,15.54,11.5,10.37,14.58,15.59,14.09
1961-01-13,1961-01-13,9.92,3.54,8.46,2.96,2.29,0.96,4.63,0.58,2.33,3.37,5.25,7.04
1961-01-14,1961-01-14,9.04,5.66,7.08,0.67,2.71,1.38,3.08,2.58,0.5,2.67,7.17,5.17
1961-01-15,1961-01-15,12.04,9.67,11.75,2.37,7.38,3.13,2.5,6.83,4.75,5.63,7.54,6.75
1961-01-16,1961-01-16,16.42,11.25,15.67,4.71,11.34,6.92,9.25,8.79,8.21,7.33,13.04,9.04
1961-01-17,1961-01-17,17.75,14.37,17.33,10.13,13.96,13.37,13.42,11.04,8.71,11.38,15.92,16.08
1961-01-18,1961-01-18,19.83,12.04,20.79,18.54,NaN,10.29,17.83,11.38,14.67,16.71,8.79,17.96
1961-01-19,1961-01-19,4.92,3.42,7.29,1.04,3.67,3.17,3.71,2.79,1.92,2.71,6.87,7.83
1961-01-20,1961-01-20,9.59,11.83,7.96,1.58,7.92,5.00,3.17,4.92,3.13,3.37,6.50,6.79
1961-01-21,1961-01-21,14.33,10.25,11.92,6.13,10.04,7.67,8.04,9.17,7.04,7.87,6.75,12.42
1961-01-22,1961-01-22,9.59,5.88,9.92,2.17,6.87,5.50,9.38,7.04,6.34,7.5,10.88,9.92
1961-01-23,1961-01-23,16.54,9.96,18.54,10.46,13.5,12.67,13.7,13.75,10.75,13.17,14.79,20.58
1961-01-24,1961-01-24,25.04,14.83,25.84,15.67,21.46,18.58,20.38,19.38,15.37,15.12,23.09,25.25
1961-01-25,1961-01-25,13.62,11.17,12.67,6.04,10,9.42,9.25,8.71,7.12,12.04,14.04,17.5
1961-01-26,1961-01-26,24.37,18.79,17.5,14.25,18.91,15.67,14.33,15.16,16.08,19.08,20.50,25.25
1961-01-27,1961-01-27,22.04,20.79,17.41,16.21,19.04,16.13,16.79,18.29,18.66,19.08,26.08,27.63
1961-01-28,1961-01-28,17.67,13.54,13.33,8.87,15.04,11.63,12.25,10.58,11.92,11.04,20.30,18.12
1961-01-29,1961-01-29,NaN,23.91,22.29,17.54,24.08,19.70,22,20.25,21.46,19.95,27.71,23.38
1961-01-30,1961-01-30,12.21,11.42,10.92,7.92,13.08,9.62,14.5,10.21,9.92,11.96,18.88,19.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-02,1978-12-02,13.7,12.71,14.29,5.13,9.21,8.04,12.33,6.34,9.21,11.21,9.59,19.95
1978-12-03,1978-12-03,21.21,21.34,17.75,11.58,16.75,14.46,17.46,15.29,15.79,17.5,21.42,25.75
1978-12-04,1978-12-04,9.92,13.5,7.21,1.71,11,7.50,8.38,7.46,10.79,10.21,17.88,17.96
1978-12-05,1978-12-05,22.75,20.17,18.58,8.5,15.96,14.29,13.92,12.92,12.96,12.29,17.08,19.83
1978-12-06,1978-12-06,29.33,23.87,25.37,16.04,24.46,19.50,24.54,18.58,21,20.58,21.67,34.46
1978-12-07,1978-12-07,26.63,24.79,24.79,18.16,23.13,19.58,19.92,19.04,19.75,21.5,23.04,34.59
1978-12-08,1978-12-08,12.92,12.54,11.25,3.37,6.5,5.96,10.34,6.17,6.63,6.75,9.54,17.33
1978-12-09,1978-12-09,18.71,16.92,15.5,6.04,10.37,9.59,10.75,9.13,9.75,11.08,14.33,15.34
1978-12-10,1978-12-10,24.92,22.54,16.54,14.62,15.59,13.00,13.21,14.12,16.21,16.17,26.08,21.92
1978-12-11,1978-12-11,20.25,19.17,17.83,11.63,17.79,13.37,14.83,13.88,15.54,16.29,18.34,22.83
1978-12-12,1978-12-12,23.13,18.63,18.05,8.29,14.33,11.04,10.54,10.13,11.42,10.5,11.25,13.5
1978-12-13,1978-12-13,18.84,24.04,14.37,8.33,18.12,12.17,13,13.75,14.17,15.09,21.50,21.37
1978-12-14,1978-12-14,17.21,19.75,12.71,5.83,13.79,7.33,8.83,5.71,7.96,3.37,5.21,6.92
1978-12-15,1978-12-15,13.13,8.92,16.54,6.92,6,4.00,12.67,5.88,7.67,6.08,5.50,17.16
1978-12-16,1978-12-16,14.88,9.13,17.37,5.21,6.71,2.46,9.13,4.96,6.13,5.96,10.92,18.08
1978-12-17,1978-12-17,9.87,3.21,8.04,2.21,3.04,0.54,2.46,1.46,1.29,2.67,5.00,9.08
1978-12-18,1978-12-18,9.83,10.88,8.5,1,9.08,6.00,2.42,8.25,4.42,5.88,19.79,19.79
1978-12-19,1978-12-19,13.88,11.42,10.13,2.33,8.12,6.75,4.75,5.88,6.21,8.17,8.33,18.25
1978-12-20,1978-12-20,9.92,3.63,12.38,3.08,3.5,0.42,4.54,2.5,2.13,4.71,3.21,10.29
1978-12-21,1978-12-21,12.96,3.83,13.79,4.79,7.12,6.54,11.67,9.25,8.67,9,11.25,20.3
1978-12-22,1978-12-22,6.21,7.38,13.08,2.54,7.58,5.33,2.46,8.38,5.09,5.04,9.92,11
1978-12-23,1978-12-23,16.62,13.29,22.21,9.5,14.29,13.08,16.5,17.16,12.71,12,18.50,21.5
1978-12-24,1978-12-24,8.67,5.63,12.12,4.79,5.09,5.91,12.25,9.25,10.83,11.71,11.92,31.71
1978-12-25,1978-12-25,7.21,6.58,7.83,2.67,4.79,4.58,8.71,0.75,5.21,5.25,1.21,13.96
1978-12-26,1978-12-26,13.83,11.87,10.34,2.37,6.96,4.29,1.96,3.79,3.04,3.08,4.79,11.96
1978-12-27,1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14,17.21,40.08
1978-12-28,1978-12-28,13.21,5.46,13.46,5,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
1978-12-29,1978-12-29,14,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.5,16.42,18.88,29.58
1978-12-30,1978-12-30,18.5,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
1978-12-31,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 7. Compute how many non-missing values there are in total.

In [79]:
data.notnull().sum()

Corrected_year    6574
RPT               6568
VAL               6571
ROS               6572
KIL               6569
SHA               6572
BIR               6574
DUB               6571
CLA               6572
MUL               6571
CLO               6573
BEL               6574
MAL               6570
dtype: int64

### Step 8. Calculate the mean windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [82]:
# Pandas will automatically exclude NaN numbers from aggregation functions
data.mean()

RPT    12.362987
VAL    10.644314
ROS    11.660526
KIL     6.306468
SHA    10.455834
BIR     7.092254
DUB     9.797343
CLA     8.495053
MUL     8.493590
CLO     8.707332
BEL    13.121007
MAL    15.599079
dtype: float64

In [83]:
data.mean().sum()

122.73578833004309

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [1]:
data['corrected_year'].min()

NameError: name 'data' is not defined

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [105]:
day_stats = data.sort_values(by='corrected_year').mean()

KeyError: 'corrected_year'

In [86]:
day_stats

RPT    12.362987
VAL    10.644314
ROS    11.660526
KIL     6.306468
SHA    10.455834
BIR     7.092254
DUB     9.797343
CLA     8.495053
MUL     8.493590
CLO     8.707332
BEL    13.121007
MAL    15.599079
dtype: float64

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [2]:
sel = data.loc['19610101':'19610131'].mean()

NameError: name 'data' is not defined

In [1]:
sel.sum()

NameError: name 'sel' is not defined

In [111]:
Jan62 = data.loc['19620101':'19620131'].mean()
Jan62

RPT    14.783871
VAL    13.160323
ROS    12.591935
KIL     7.538065
SHA    11.779677
BIR     8.720000
DUB    14.211935
CLA     9.600000
MUL     9.670000
CLO    11.498710
BEL    16.369355
MAL    15.661613
dtype: float64

In [120]:
Jan63 = data.loc['19630101':'19630131'].mean()
Jan63

RPT    14.868387
VAL    11.112903
ROS    15.121613
KIL     6.635806
SHA    11.080645
BIR     7.835484
DUB    12.797419
CLA     9.844839
MUL     7.841613
CLO     9.390000
BEL    11.428710
MAL    18.822258
dtype: float64

In [139]:
grouped = data.groupby(data['Corrected_year'])['RPT','VAL','ROS','KIL','SHA','BIR','DUB','CLA','MUL','CLO','BEL','MAL'].agg(['min','max','mean','std'])
grouped

                  RPT                      VAL                      ROS  \
                  min    max   mean std    min    max   mean std    min
Corrected_year
1961-01-01      15.04  15.04  15.04 NaN  14.96  14.96  14.96 NaN  13.17
1961-01-02      14.71  14.71  14.71 NaN    NaN    NaN    NaN NaN  10.83
1961-01-03      18.50  18.50  18.50 NaN  16.88  16.88  16.88 NaN  12.33
1961-01-04      10.58  10.58  10.58 NaN   6.63   6.63   6.63 NaN  11.75
1961-01-05      13.33  13.33  13.33 NaN  13.25  13.25  13.25 NaN  11.42
1961-01-06      13.21  13.21  13.21 NaN   8.12   8.12   8.12 NaN   9.96
1961-01-07      13.50  13.50  13.50 NaN  14.29  14.29  14.29 NaN   9.50
1961-01-08      10.96  10.96  10.96 NaN   9.75   9.75   9.75 NaN   7.62
1961-01-09      12.58  12.58  12.58 NaN  10.83  10.83  10.83 NaN  10.00
1961-01-10      13.37  13.37  13.37 NaN  11.12  11.12  11.12 NaN  19.50
1961-01-11      10.58  10.58  10.58 NaN   9.87   9.87   9.87 NaN   8.42
1961-01-12      19.75  19.75  19.75 NaN  12.08  12.08  12.08 NaN  18.50
1961-01-13       9.92   9.92   9.92 NaN   3.54   3.54   3.54 NaN   8.46
1961-01-14       9.04   9.04   9.04 NaN   5.66   5.66   5.66 NaN   7.08
1961-01-15      12.04  12.04  12.04 NaN   9.67   9.67   9.67 NaN  11.75
1961-01-16      16.42  16.42  16.42 NaN  11.25  11.25  11.25 NaN  15.67
1961-01-17      17.75  17.75  17.75 NaN  14.37  14.37  14.37 NaN  17.33
1961-01-18      19.83  19.83  19.83 NaN  12.04  12.04  12.04 NaN  20.79
1961-01-19       4.92   4.92   4.92 NaN   3.42   3.42   3.42 NaN   7.29
1961-01-20       9.59   9.59   9.59 NaN  11.83  11.83  11.83 NaN   7.96
1961-01-21      14.33  14.33  14.33 NaN  10.25  10.25  10.25 NaN  11.92
1961-01-22       9.59   9.59   9.59 NaN   5.88   5.88   5.88 NaN   9.92
1961-01-23      16.54  16.54  16.54 NaN   9.96   9.96   9.96 NaN  18.54
1961-01-24      25.04  25.04  25.04 NaN  14.83  14.83  14.83 NaN  25.84
1961-01-25      13.62  13.62  13.62 NaN  11.17  11.17  11.17 NaN  12.67
1961-01-26      24.37  24.37  24.37 NaN  18.79  18.79  18.79 NaN  17.50
1961-01-27      22.04  22.04  22.04 NaN  20.79  20.79  20.79 NaN  17.41
1961-01-28      17.67  17.67  17.67 NaN  13.54  13.54  13.54 NaN  13.33
1961-01-29        NaN    NaN    NaN NaN  23.91  23.91  23.91 NaN  22.29
1961-01-30      12.21  12.21  12.21 NaN  11.42  11.42  11.42 NaN  10.92
...               ...    ...    ...  ..    ...    ...    ...  ..    ...
1978-12-02      13.70  13.70  13.70 NaN  12.71  12.71  12.71 NaN  14.29
1978-12-03      21.21  21.21  21.21 NaN  21.34  21.34  21.34 NaN  17.75
1978-12-04       9.92   9.92   9.92 NaN  13.50  13.50  13.50 NaN   7.21
1978-12-05      22.75  22.75  22.75 NaN  20.17  20.17  20.17 NaN  18.58
1978-12-06      29.33  29.33  29.33 NaN  23.87  23.87  23.87 NaN  25.37
1978-12-07      26.63  26.63  26.63 NaN  24.79  24.79  24.79 NaN  24.79
1978-12-08      12.92  12.92  12.92 NaN  12.54  12.54  12.54 NaN  11.25
1978-12-09      18.71  18.71  18.71 NaN  16.92  16.92  16.92 NaN  15.50
1978-12-10      24.92  24.92  24.92 NaN  22.54  22.54  22.54 NaN  16.54
1978-12-11      20.25  20.25  20.25 NaN  19.17  19.17  19.17 NaN  17.83
1978-12-12      23.13  23.13  23.13 NaN  18.63  18.63  18.63 NaN  18.05
1978-12-13      18.84  18.84  18.84 NaN  24.04  24.04  24.04 NaN  14.37
1978-12-14      17.21  17.21  17.21 NaN  19.75  19.75  19.75 NaN  12.71
1978-12-15      13.13  13.13  13.13 NaN   8.92   8.92   8.92 NaN  16.54
1978-12-16      14.88  14.88  14.88 NaN   9.13   9.13   9.13 NaN  17.37
1978-12-17       9.87   9.87   9.87 NaN   3.21   3.21   3.21 NaN   8.04
1978-12-18       9.83   9.83   9.83 NaN  10.88  10.88  10.88 NaN   8.50
1978-12-19      13.88  13.88  13.88 NaN  11.42  11.42  11.42 NaN  10.13
1978-12-20       9.92   9.92   9.92 NaN   3.63   3.63   3.63 NaN  12.38
1978-12-21      12.96  12.96  12.96 NaN   3.83   3.83   3.83 NaN  13.79
1978-12-22       6.21   6.21   6.21 NaN   7.38   7.38   7.38 NaN  13.08
1978-12-23      16.62  16.62  16.62 NaN  13.29  13.29  13.29 NaN  22.21
1978-12-24       8.67   8.67   8.67 NaN   5.63   5.63   5.63 NaN  12.12
1978-12-25       7.21   7.21   7.21 NaN   6.58   6.58   6.58 NaN   7.83
1978-12-26      13.83  13.83  13.83 NaN  11.87  11.87  11.87 NaN  10.34
1978-12-27      17.58  17.58  17.58 NaN  16.96  16.96  16.96 NaN  17.62
1978-12-28      13.21  13.21  13.21 NaN   5.46   5.46   5.46 NaN  13.46
1978-12-29      14.00  14.00  14.00 NaN  10.29  10.29  10.29 NaN  14.42
1978-12-30      18.50  18.50  18.50 NaN  14.04  14.04  14.04 NaN  21.29
1978-12-31      20.33  20.33  20.33 NaN  17.41  17.41  17.41 NaN  27.29

                       ...    CLO        BEL                      MAL         \
                  max  ...   mean std    min    max   mean std    min    max
Corrected_year         ...
1961-01-01      13.17  ...  12.58 NaN  18.50  18.50  18.50 NaN  15.04  15.04
1961-01-02      10.83  ...   9.67 NaN  17.54  17.54  17.54 NaN  13.83  13.83
1961-01-03      12.33  ...   7.67 NaN  12.75  12.75  12.75 NaN  12.71  12.71
1961-01-04      11.75  ...   5.88 NaN   5.46   5.46   5.46 NaN  10.88  10.88
1961-01-05      11.42  ...  10.34 NaN  12.92  12.92  12.92 NaN  11.83  11.83
1961-01-06       9.96  ...   7.50 NaN   8.12   8.12   8.12 NaN  13.17  13.17
1961-01-07       9.50  ...   7.96 NaN  13.96  13.96  13.96 NaN  13.79  13.79
1961-01-08       7.62  ...  10.46 NaN  16.62  16.62  16.62 NaN  16.46  16.46
1961-01-09      10.00  ...   9.08 NaN  13.04  13.04  13.04 NaN  15.37  15.37
1961-01-10      19.50  ...   9.00 NaN   8.58   8.58   8.58 NaN  11.83  11.83
1961-01-11       8.42  ...   8.67 NaN  20.71  20.71  20.71 NaN  16.92  16.92
1961-01-12      18.50  ...  14.58 NaN  15.59  15.59  15.59 NaN  14.09  14.09
1961-01-13       8.46  ...   3.37 NaN   5.25   5.25   5.25 NaN   7.04   7.04
1961-01-14       7.08  ...   2.67 NaN   7.17   7.17   7.17 NaN   5.17   5.17
1961-01-15      11.75  ...   5.63 NaN   7.54   7.54   7.54 NaN   6.75   6.75
1961-01-16      15.67  ...   7.33 NaN  13.04  13.04  13.04 NaN   9.04   9.04
1961-01-17      17.33  ...  11.38 NaN  15.92  15.92  15.92 NaN  16.08  16.08
1961-01-18      20.79  ...  16.71 NaN   8.79   8.79   8.79 NaN  17.96  17.96
1961-01-19       7.29  ...   2.71 NaN   6.87   6.87   6.87 NaN   7.83   7.83
1961-01-20       7.96  ...   3.37 NaN   6.50   6.50   6.50 NaN   6.79   6.79
1961-01-21      11.92  ...   7.87 NaN   6.75   6.75   6.75 NaN  12.42  12.42
1961-01-22       9.92  ...   7.50 NaN  10.88  10.88  10.88 NaN   9.92   9.92
1961-01-23      18.54  ...  13.17 NaN  14.79  14.79  14.79 NaN  20.58  20.58
1961-01-24      25.84  ...  15.12 NaN  23.09  23.09  23.09 NaN  25.25  25.25
1961-01-25      12.67  ...  12.04 NaN  14.04  14.04  14.04 NaN  17.50  17.50
1961-01-26      17.50  ...  19.08 NaN  20.50  20.50  20.50 NaN  25.25  25.25
1961-01-27      17.41  ...  19.08 NaN  26.08  26.08  26.08 NaN  27.63  27.63
1961-01-28      13.33  ...  11.04 NaN  20.30  20.30  20.30 NaN  18.12  18.12
1961-01-29      22.29  ...  19.95 NaN  27.71  27.71  27.71 NaN  23.38  23.38
1961-01-30      10.92  ...  11.96 NaN  18.88  18.88  18.88 NaN  19.25  19.25
...               ...  ...    ...  ..    ...    ...    ...  ..    ...    ...
1978-12-02      14.29  ...  11.21 NaN   9.59   9.59   9.59 NaN  19.95  19.95
1978-12-03      17.75  ...  17.50 NaN  21.42  21.42  21.42 NaN  25.75  25.75
1978-12-04       7.21  ...  10.21 NaN  17.88  17.88  17.88 NaN  17.96  17.96
1978-12-05      18.58  ...  12.29 NaN  17.08  17.08  17.08 NaN  19.83  19.83
1978-12-06      25.37  ...  20.58 NaN  21.67  21.67  21.67 NaN  34.46  34.46
1978-12-07      24.79  ...  21.50 NaN  23.04  23.04  23.04 NaN  34.59  34.59
1978-12-08      11.25  ...   6.75 NaN   9.54   9.54   9.54 NaN  17.33  17.33
1978-12-09      15.50  ...  11.08 NaN  14.33  14.33  14.33 NaN  15.34  15.34
1978-12-10      16.54  ...  16.17 NaN  26.08  26.08  26.08 NaN  21.92  21.92
1978-12-11      17.83  ...  16.29 NaN  18.34  18.34  18.34 NaN  22.83  22.83
1978-12-12      18.05  ...  10.50 NaN  11.25  11.25  11.25 NaN  13.50  13.50
1978-12-13      14.37  ...  15.09 NaN  21.50  21.50  21.50 NaN  21.37  21.37
1978-12-14      12.71  ...   3.37 NaN   5.21   5.21   5.21 NaN   6.92   6.92
1978-12-15      16.54  ...   6.08 NaN   5.50   5.50   5.50 NaN  17.16  17.16
1978-12-16      17.37  ...   5.96 NaN  10.92  10.92  10.92 NaN  18.08  18.08
1978-12-17       8.04  ...   2.67 NaN   5.00   5.00   5.00 NaN   9.08   9.08
1978-12-18       8.50  ...   5.88 NaN  19.79  19.79  19.79 NaN  19.79  19.79
1978-12-19      10.13  ...   8.17 NaN   8.33   8.33   8.33 NaN  18.25  18.25
1978-12-20      12.38  ...   4.71 NaN   3.21   3.21   3.21 NaN  10.29  10.29
1978-12-21      13.79  ...   9.00 NaN  11.25  11.25  11.25 NaN  20.30  20.30
1978-12-22      13.08  ...   5.04 NaN   9.92   9.92   9.92 NaN  11.00  11.00
1978-12-23      22.21  ...  12.00 NaN  18.50  18.50  18.50 NaN  21.50  21.50
1978-12-24      12.12  ...  11.71 NaN  11.92  11.92  11.92 NaN  31.71  31.71
1978-12-25       7.83  ...   5.25 NaN   1.21   1.21   1.21 NaN  13.96  13.96
1978-12-26      10.34  ...   3.08 NaN   4.79   4.79   4.79 NaN  11.96  11.96
1978-12-27      17.62  ...  14.00 NaN  17.21  17.21  17.21 NaN  40.08  40.08
1978-12-28      13.46  ...  18.05 NaN  21.79  21.79  21.79 NaN  41.46  41.46
1978-12-29      14.42  ...  16.42 NaN  18.88  18.88  18.88 NaN  29.58  29.58
1978-12-30      21.29  ...  12.12 NaN  14.67  14.67  14.67 NaN  28.79  28.79
1978-12-31      27.29  ...  11.38 NaN  12.08  12.08  12.08 NaN  22.08  22.08


                 mean std
Corrected_year
1961-01-01      15.04 NaN
1961-01-02      13.83 NaN
1961-01-03      12.71 NaN
1961-01-04      10.88 NaN
1961-01-05      11.83 NaN
1961-01-06      13.17 NaN
1961-01-07      13.79 NaN
1961-01-08      16.46 NaN
1961-01-09      15.37 NaN
1961-01-10      11.83 NaN
1961-01-11      16.92 NaN
1961-01-12      14.09 NaN
1961-01-13       7.04 NaN
1961-01-14       5.17 NaN
1961-01-15       6.75 NaN
1961-01-16       9.04 NaN
1961-01-17      16.08 NaN
1961-01-18      17.96 NaN
1961-01-19       7.83 NaN
1961-01-20       6.79 NaN
1961-01-21      12.42 NaN
1961-01-22       9.92 NaN
1961-01-23      20.58 NaN
1961-01-24      25.25 NaN
1961-01-25      17.50 NaN
1961-01-26      25.25 NaN
1961-01-27      27.63 NaN
1961-01-28      18.12 NaN
1961-01-29      23.38 NaN
1961-01-30      19.25 NaN
...               ...  ..
1978-12-02      19.95 NaN
1978-12-03      25.75 NaN
1978-12-04      17.96 NaN
1978-12-05      19.83 NaN
1978-12-06      34.46 NaN
1978-12-07      34.59 NaN
1978-12-08      17.33 NaN
1978-12-09      15.34 NaN
1978-12-10      21.92 NaN
1978-12-11      22.83 NaN
1978-12-12      13.50 NaN
1978-12-13      21.37 NaN
1978-12-14       6.92 NaN
1978-12-15      17.16 NaN
1978-12-16      18.08 NaN
1978-12-17       9.08 NaN
1978-12-18      19.79 NaN
1978-12-19      18.25 NaN
1978-12-20      10.29 NaN
1978-12-21      20.30 NaN
1978-12-22      11.00 NaN
1978-12-23      21.50 NaN
1978-12-24      31.71 NaN
1978-12-25      13.96 NaN
1978-12-26      11.96 NaN
1978-12-27      40.08 NaN
1978-12-28      41.46 NaN
1978-12-29      29.58 NaN
1978-12-30      28.79 NaN
1978-12-31      22.08 NaN

[6574 rows x 48 columns]

In [152]:
data.dtypes

data=data.drop(['Corrected_year'],axis = 1)

KeyError: "['Corrected_year'] not found in axis"

In [163]:
#data.groupby([['RPT','VAL','ROS']]).mean()
# data['Mean Locations'] = data.mean(axis=1)

data.loc['Mean_columns'] = data.mean()
data

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,Mean Locations
Corrected_year,,,,,,,,,,,,,
1961-01-01 00:00:00,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.83000,12.580000,18.500000,15.040000,13.018182
1961-01-02 00:00:00,14.710000,NaN,10.830000,6.500000,12.620000,7.670000,11.500000,10.040000,9.79000,9.670000,17.540000,13.830000,11.336364
1961-01-03 00:00:00,18.500000,16.880000,12.330000,10.130000,11.170000,6.170000,11.250000,NaN,8.50000,7.670000,12.750000,12.710000,11.641818
1961-01-04 00:00:00,10.580000,6.630000,11.750000,4.580000,4.540000,2.880000,8.630000,1.790000,5.83000,5.880000,5.460000,10.880000,6.619167
1961-01-05 00:00:00,13.330000,13.250000,11.420000,6.170000,10.710000,8.210000,11.920000,6.540000,10.92000,10.340000,12.920000,11.830000,10.630000
1961-01-06 00:00:00,13.210000,8.120000,9.960000,6.670000,5.370000,4.500000,10.670000,4.420000,7.17000,7.500000,8.120000,13.170000,8.240000
1961-01-07 00:00:00,13.500000,14.290000,9.500000,4.960000,12.290000,8.330000,9.170000,9.290000,7.58000,7.960000,13.960000,13.790000,10.385000
1961-01-08 00:00:00,10.960000,9.750000,7.620000,5.910000,9.620000,7.290000,14.290000,7.620000,9.25000,10.460000,16.620000,16.460000,10.487500
1961-01-09 00:00:00,12.580000,10.830000,10.000000,4.750000,10.370000,6.790000,8.040000,10.130000,7.79000,9.080000,13.040000,15.370000,9.897500
1961-01-10 00:00:00,13.370000,11.120000,19.500000,8.330000,9.710000,6.540000,11.420000,7.790000,8.54000,9.000000,8.580000,11.830000,10.477500
1961-01-11 00:00:00,10.580000,9.870000,8.420000,2.790000,8.710000,7.250000,7.540000,8.330000,5.71000,8.670000,20.710000,16.920000,9.625000
1961-01-12 00:00:00,19.750000,12.080000,18.500000,10.540000,10.290000,9.460000,15.540000,11.500000,10.37000,14.580000,15.590000,14.090000,13.524167
1961-01-13 00:00:00,9.920000,3.540000,8.460000,2.960000,2.290000,0.960000,4.630000,0.580000,2.33000,3.370000,5.250000,7.040000,4.277500
1961-01-14 00:00:00,9.040000,5.660000,7.080000,0.670000,2.710000,1.380000,3.080000,2.580000,0.50000,2.670000,7.170000,5.170000,3.975833
1961-01-15 00:00:00,12.040000,9.670000,11.750000,2.370000,7.380000,3.130000,2.500000,6.830000,4.75000,5.630000,7.540000,6.750000,6.695000
1961-01-16 00:00:00,16.420000,11.250000,15.670000,4.710000,11.340000,6.920000,9.250000,8.790000,8.21000,7.330000,13.040000,9.040000,10.164167
1961-01-17 00:00:00,17.750000,14.370000,17.330000,10.130000,13.960000,13.370000,13.420000,11.040000,8.71000,11.380000,15.920000,16.080000,13.621667
1961-01-18 00:00:00,19.830000,12.040000,20.790000,18.540000,NaN,10.290000,17.830000,11.380000,14.67000,16.710000,8.790000,17.960000,15.348182
1961-01-19 00:00:00,4.920000,3.420000,7.290000,1.040000,3.670000,3.170000,3.710000,2.790000,1.92000,2.710000,6.870000,7.830000,4.111667
1961-01-20 00:00:00,9.590000,11.830000,7.960000,1.580000,7.920000,5.000000,3.170000,4.920000,3.13000,3.370000,6.500000,6.790000,5.980000
1961-01-21 00:00:00,14.330000,10.250000,11.920000,6.130000,10.040000,7.670000,8.040000,9.170000,7.04000,7.870000,6.750000,12.420000,9.302500
1961-01-22 00:00:00,9.590000,5.880000,9.920000,2.170000,6.870000,5.500000,9.380000,7.040000,6.34000,7.500000,10.880000,9.920000,7.582500
1961-01-23 00:00:00,16.540000,9.960000,18.540000,10.460000,13.500000,12.670000,13.700000,13.750000,10.75000,13.170000,14.790000,20.580000,14.034167
1961-01-24 00:00:00,25.040000,14.830000,25.840000,15.670000,21.460000,18.580000,20.380000,19.380000,15.37000,15.120000,23.090000,25.250000,20.000833
1961-01-25 00:00:00,13.620000,11.170000,12.670000,6.040000,10.000000,9.420000,9.250000,8.710000,7.12000,12.040000,14.040000,17.500000,10.965000
1961-01-26 00:00:00,24.370000,18.790000,17.500000,14.250000,18.910000,15.670000,14.330000,15.160000,16.08000,19.080000,20.500000,25.250000,18.324167
1961-01-27 00:00:00,22.040000,20.790000,17.410000,16.210000,19.040000,16.130000,16.790000,18.290000,18.66000,19.080000,26.080000,27.630000,19.845833
1961-01-28 00:00:00,17.670000,13.540000,13.330000,8.870000,15.040000,11.630000,12.250000,10.580000,11.92000,11.040000,20.300000,18.120000,13.690833
1961-01-29 00:00:00,NaN,23.910000,22.290000,17.540000,24.080000,19.700000,22.000000,20.250000,21.46000,19.950000,27.710000,23.380000,22.024545
1961-01-30 00:00:00,12.210000,11.420000,10.920000,7.920000,13.080000,9.620000,14.500000,10.210000,9.92000,11.960000,18.880000,19.250000,12.490833
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-04 00:00:00,9.920000,13.500000,7.210000,1.710000,11.000000,7.500000,8.380000,7.460000,10.79000,10.210000,17.880000,17.960000,10.293333
1978-12-05 00:00:00,22.750000,20.170000,18.580000,8.500000,15.960000,14.290000,13.920000,12.920000,12.96000,12.290000,17.080000,19.830000,15.770833
1978-12-06 00:00:00,29.330000,23.870000,25.370000,16.040000,24.460000,19.500000,24.540000,18.580000,21.00000,20.580000,21.670000,34.460000,23.283333
1978-12-07 00:00:00,26.630000,24.790000,24.790000,18.160000,23.130000,19.580000,19.920000,19.040000,19.75000,21.500000,23.040000,34.590000,22.910000
1978-12-08 00:00:00,12.920000,12.540000,11.250000,3.370000,6.500000,5.960000,10.340000,6.170000,6.63000,6.750000,9.540000,17.330000,9.108333
1978-12-09 00:00:00,18.710000,16.920000,15.500000,6.040000,10.370000,9.590000,10.750000,9.130000,9.75000,11.080000,14.330000,15.340000,12.292500
1978-12-10 00:00:00,24.920000,22.540000,16.540000,14.620000,15.590000,13.000000,13.210000,14.120000,16.21000,16.170000,26.080000,21.920000,17.910000
1978-12-11 00:00:00,20.250000,19.170000,17.830000,11.630000,17.790000,13.370000,14.830000,13.880000,15.54000,16.290000,18.340000,22.830000,16.812500
1978-12-12 00:00:00,23.130000,18.630000,18.050000,8.290000,14.330000,11.040000,10.540000,10.130000,11.42000,10.500000,11.250000,13.500000,13.400833
1978-12-13 00:00:00,18.840000,24.040000,14.370000,8.330000,18.120000,12.170000,13.000000,13.750000,14.17000,15.090000,21.500000,21.370000,16.229167
1978-12-14 00:00:00,17.210000,19.750000,12.710000,5.830000,13.790000,7.330000,8.830000,5.710000,7.96000,3.370000,5.210000,6.920000,9.551667
1978-12-15 00:00:00,13.130000,8.920000,16.540000,6.920000,6.000000,4.000000,12.670000,5.880000,7.67000,6.080000,5.500000,17.160000,9.205833
1978-12-16 00:00:00,14.880000,9.130000,17.370000,5.210000,6.710000,2.460000,9.130000,4.960000,6.13000,5.960000,10.920000,18.080000,9.245000
1978-12-17 00:00:00,9.870000,3.210000,8.040000,2.210000,3.040000,0.540000,2.460000,1.460000,1.29000,2.670000,5.000000,9.080000,4.072500
1978-12-18 00:00:00,9.830000,10.880000,8.500000,1.000000,9.080000,6.000000,2.420000,8.250000,4.42000,5.880000,19.790000,19.790000,8.820000
1978-12-19 00:00:00,13.880000,11.420000,10.130000,2.330000,8.120000,6.750000,4.750000,5.880000,6.21000,8.170000,8.330000,18.250000,8.685000
1978-12-20 00:00:00,9.920000,3.630000,12.380000,3.080000,3.500000,0.420000,4.540000,2.500000,2.13000,4.710000,3.210000,10.290000,5.025833
1978-12-21 00:00:00,12.960000,3.830000,13.790000,4.790000,7.120000,6.540000,11.670000,9.250000,8.67000,9.000000,11.250000,20.300000,9.930833
1978-12-22 00:00:00,6.210000,7.380000,13.080000,2.540000,7.580000,5.330000,2.460000,8.380000,5.09000,5.040000,9.920000,11.000000,7.000833
1978-12-23 00:00:00,16.620000,13.290000,22.210000,9.500000,14.290000,13.080000,16.500000,17.160000,12.71000,12.000000,18.500000,21.500000,15.613333
1978-12-24 00:00:00,8.670000,5.630000,12.120000,4.790000,5.090000,5.910000,12.250000,9.250000,10.83000,11.710000,11.920000,31.710000,10.823333
1978-12-25 00:00:00,7.210000,6.580000,7.830000,2.670000,4.790000,4.580000,8.710000,0.750000,5.21000,5.250000,1.210000,13.960000,5.729167
1978-12-26 00:00:00,13.830000,11.870000,10.340000,2.370000,6.960000,4.290000,1.960000,3.790000,3.04000,3.080000,4.790000,11.960000,6.523333
1978-12-27 00:00:00,17.580000,16.960000,17.620000,8.080000,13.210000,11.670000,14.460000,15.590000,14.04000,14.000000,17.210000,40.080000,16.708333
1978-12-28 00:00:00,13.210000,5.460000,13.460000,5.000000,8.120000,9.420000,14.330000,16.250000,15.25000,18.050000,21.790000,41.460000,15.150000
1978-12-29 00:00:00,14.000000,10.290000,14.420000,8.710000,9.710000,10.540000,19.170000,12.460000,14.50000,16.420000,18.880000,29.580000,14.890000
1978-12-30 00:00:00,18.500000,14.040000,21.290000,9.130000,12.750000,9.710000,18.080000,12.870000,12.46000,12.120000,14.670000,28.790000,15.367500
1978-12-31 00:00:00,20.330000,17.410000,27.290000,9.590000,12.080000,10.130000,19.250000,11.630000,11.58000,11.380000,12.080000,22.080000,15.402500
Mean_rowise,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.49359,8.707332,13.121007,15.599079,10.228284
Mean_columns,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.49359,8.707332,13.121007,15.599079,10.228284

In [3]:
#grouped1 = data.loc[[[['RPT','VAL','ROS','KIL','SHA','BIR','DUB','CLA','MUL','CLO','BEL','MAL']].agg(['min','max','mean','std']),]]
#grouped1
data.mean()

NameError: name 'data' is not defined

### Step 12. Downsample the record to a yearly frequency for each location.

In [185]:
data[['RPT','VAL']].min()

RPT    0.67
VAL    0.21
dtype: float64

In [183]:
data.loc[:,'RPT'].min()

0.67

### Step 13. Downsample the record to a monthly frequency for each location.

In [143]:
type(data['Corrected_year'])
data.dtypes

Corrected_year    datetime64[ns]
RPT                      float64
VAL                      float64
ROS                      float64
KIL                      float64
SHA                      float64
BIR                      float64
DUB                      float64
CLA                      float64
MUL                      float64
CLO                      float64
BEL                      float64
MAL                      float64
dtype: object

### Step 14. Downsample the record to a weekly frequency for each location.

### Step 15. Calculate the mean windspeed for each month in the dataset.  
#### Treat January 1961 and January 1962 as *different* months.
#### (hint: first find a  way to create an identifier unique for each month.)

In [169]:
data['1961']

KeyError: '1961'

# Step 16. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.